backend:
  name: proxy
  proxy_url: http://localhost:43999/api/v1
  branch: master

local_backend:
  url: http://localhost:43999/api/v1
  allowed_hosts: ['localhost']

media_folder: '/public/img/content/posts'
public_folder: '/img/content/posts'

collections:
  - name: 'tags'
    label: 'Tags'
    folder: 'content/tags'
    create: true
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Icon', name: 'icon', widget: 'image', required: false }
      - {
          label: 'Featured?',
          name: 'featured',
          widget: 'boolean',
          default: false,
          required: false,
        }

  - name: 'authors'
    label: 'Authors'
    folder: 'content/authors'
    create: true
    slug: '{{name}}'
    summary: '{{name}} - T:{{twitter}}'
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
      - { label: 'Github', name: 'github', widget: 'string', required: false }
      - {
          label: 'LinkedIn',
          name: 'linkedin',
          widget: 'string',
          required: false,
        }
      - { label: 'Medium', name: 'medium', widget: 'string', required: false }
      - { label: 'GPG Key', name: 'gpgKey', widget: 'string', required: false }
      - {
          label: 'Clubhouse',
          name: 'clubhouse',
          widget: 'string',
          required: false,
        }
      - { label: 'YouTube', name: 'youtube', widget: 'string', required: false }
      - {
          label: 'Profile picture',
          name: 'profilePicture',
          widget: 'image',
          required: true,
          media_folder: '/public/img/content/authors',
          public_folder: '/img/content/authors',
        }
      - {
          label: 'Short bio',
          name: 'shortBio',
          widget: 'string',
          require: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{slug}}'
    sortable_fields: ['publishedOn', 'title']
    summary: '{{publishedOn}} - {{title}}'
    fields:
      - {
          label: 'Published on',
          name: 'publishedOn',
          widget: 'datetime',
          required: false,
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Sub title',
          name: 'subTitle',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Canonical URL',
          name: 'canonicalUrl',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Featured?',
          name: 'featured',
          widget: 'boolean',
          default: false,
          required: false,
        }
      - {
          label: 'Hero image',
          name: 'heroImg',
          widget: 'image',
          required: true,
          media_folder: '/public/img/content/posts',
          public_folder: '/img/content/posts',
        }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'relation',
          collection: 'tags',
          search_fields: ['title'],
          value_field: 'slug',
          display_fields: ['title'],
          multiple: true,
        }
      - {
          label: 'Related posts',
          name: 'relatedSlugs',
          widget: 'relation',
          collection: 'posts',
          search_fields: ['title'],
          value_field: 'slug',
          display_fields: ['title'],
          multiple: true,
          required: false,
        }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          search_fields: ['name'],
          value_field: 'slug',
          display_fields: ['name'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'microPosts'
    label: 'Micro Posts'
    folder: 'content/microPosts'
    create: true
    slug: '{{year}}-{{slug}}'
    sortable_fields: ['publishedOn', 'slug']
    summary: '{{publishedOn}} - {{slug}}'
    fields:
      - {
          label: 'Published on',
          name: 'publishedOn',
          widget: 'datetime',
          required: false,
        }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          search_fields: ['name'],
          value_field: 'slug',
          display_fields: ['name'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    sortable_fields: ['startDay', 'title']
    summary: '{{title}} - {{companyName}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Company Name', name: 'companyName', widget: 'string' }
      - { label: 'Company URL', name: 'companyUrl', widget: 'string' }
      - {
          label: 'Logo',
          name: 'logo',
          widget: 'image',
          required: true,
          media_folder: '/public/img/content/projects',
          public_folder: '/img/content/projects',
        }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Start Day',
          name: 'startDay',
          widget: 'datetime',
          required: true,
          date_format: 'YYYY-MM-DD',
          time_format: false,
        }
      - {
          label: 'End Day',
          name: 'endDay',
          widget: 'datetime',
          required: false,
          date_format: 'YYYY-MM-DD',
          time_format: false,
        }
      - { label: 'Slug', name: 'slug', widget: 'string' }
